import type { Lang } from "./types";

export const STRINGS = {
  th: {
    tagline: "นำตัวเลขมา + − × ÷ ^ √ ! Σ ให้ได้ตามเป้า",
    timePerRound: "เวลาต่อข้อ",
    custom: "กำหนดเอง",
    targetDigitsLabel: "จำนวนหลักของเป้าหมาย",
    numbersCountLabel: "จำนวนตัวเลขที่ใช้",
    digitsOption: (n: number) => `${n} หลัก`,
    digitsRange: (n: number) =>
      n === 2 ? "10 – 99" : n === 3 ? "100 – 999" : "",
    numsOption: (n: number) => `${n} ตัว`,
    startGame: "เริ่มเล่น",
    back: "เปลี่ยนการตั้งค่า",
    modeInfo: (num: number, tg: number, t: number) =>
      `${num} ตัว · ${tg} หลัก · ${t}s`,
    timeLeft: "เวลาคงเหลือ",
    timeUp: "หมดเวลา",
    paused: "หยุดชั่วคราว",
    target: "เป้าหมาย",
    numbers: "ตัวเลข",
    newPuzzle: "สุ่มโจทย์",
    showSolution: "ดูเฉลย",
    solving: "กำลังคำนวณ…",
    solutionHeading: "เฉลย",
    topSimplest: (n: number) => `${n} วิธีที่ง่ายที่สุด`,
    closestMatch: "ใกล้เคียงที่สุด",
    exact: "ตรงเป๊ะ",
    delta: (d: number) => `ต่าง ${d}`,
    noExact: (t: number) => `ไม่พบคำตอบที่ตรงกับ ${t}`,
    solutionsPlaceholder: "กด ‘ดูเฉลย’ เพื่อแสดงวิธีทำ",
    footer: "ใช้ทุกตัวเลขหนึ่งครั้ง",
    tierLabels: ["+ − × ÷", "+ ยกกำลัง", "+ √", "+ n!", "+ Σ"] as readonly string[],
    seconds: "วินาที",
    soundOn: "เสียงเปิด",
    soundOff: "เสียงปิด",
  },
  en: {
    tagline: "Combine numbers with + − × ÷ ^ √ ! Σ to hit the target",
    timePerRound: "Time per round",
    custom: "Custom",
    targetDigitsLabel: "Target digits",
    numbersCountLabel: "Number count",
    digitsOption: (n: number) => `${n}-digit`,
    digitsRange: (n: number) =>
      n === 2 ? "10 – 99" : n === 3 ? "100 – 999" : "",
    numsOption: (n: number) => `${n} nums`,
    startGame: "Start",
    back: "Change settings",
    modeInfo: (num: number, tg: number, t: number) =>
      `${num} nums · ${tg}-digit · ${t}s`,
    timeLeft: "Time left",
    timeUp: "Time's up",
    paused: "Paused",
    target: "Target",
    numbers: "Numbers",
    newPuzzle: "New puzzle",
    showSolution: "Show solution",
    solving: "Solving…",
    solutionHeading: "Solutions",
    topSimplest: (n: number) => `Top ${n} simplest`,
    closestMatch: "Closest match",
    exact: "Exact",
    delta: (d: number) => `Δ ${d}`,
    noExact: (t: number) => `No exact match for ${t}`,
    solutionsPlaceholder: "Tap ‘Show solution’ to reveal answers",
    footer: "Use each number once",
    tierLabels: ["+ − × ÷", "+ power", "+ √", "+ n!", "+ Σ"] as readonly string[],
    seconds: "sec",
    soundOn: "Sound on",
    soundOff: "Sound off",
  },
} as const;

export type Dict = (typeof STRINGS)[Lang];
